package generation

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime"
	"net"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/p-chat/pchat/internal/config"
	providerstrategy "github.com/p-chat/pchat/internal/provider"
	"github.com/p-chat/pchat/internal/requestheader"
)

const (
	defaultMaxAssetBytes  int64 = 128 << 20
	defaultMaxStoreBytes  int64 = 20 << 30
	maxAssetsPerResponse        = 4
	maxAssetResponseBytes int64 = 256 << 20
)

// InputSource is an authorized attachment or generated asset resolved from an
// opaque id. Bytes never cross the model-facing tool boundary.
type InputSource struct {
	ID       string
	Kind     config.MediaKind
	MIMEType string
	Name     string
	Data     []byte
}

// InputResolver validates conversation ownership and resolves an opaque input
// reference to bytes for the vendor adapter.
type InputResolver interface {
	ResolveInput(context.Context, string, string, config.MediaKind) (InputSource, error)
}

type storedAssetMeta struct {
	ID        string           `json:"id"`
	SessionID string           `json:"session_id"`
	Kind      config.MediaKind `json:"kind"`
	MIMEType  string           `json:"mime_type"`
	Name      string           `json:"name"`
	FileName  string           `json:"file_name"`
}

// LocalAssetStore materializes generated bytes under a durable local
// directory and exposes stable same-origin URLs to the frontend.
type LocalAssetStore struct {
	Dir       string
	URLPrefix string
	MaxBytes  int64
	mu        sync.Mutex
}

// NewLocalAssetStore creates a local generated-asset store descriptor.
func NewLocalAssetStore(dir, urlPrefix string) *LocalAssetStore {
	return &LocalAssetStore{Dir: dir, URLPrefix: strings.TrimRight(urlPrefix, "/"), MaxBytes: defaultMaxStoreBytes}
}

// Save persists one generated asset and its conversation ownership metadata.
func (s *LocalAssetStore) Save(sessionID string, kind config.MediaKind, mimeType, name string, data []byte) (Asset, error) {
	if s == nil || strings.TrimSpace(s.Dir) == "" {
		return Asset{}, errors.New("generated asset store is unavailable")
	}
	if len(data) == 0 {
		return Asset{}, errors.New("generated asset is empty")
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if err := os.MkdirAll(s.Dir, 0o755); err != nil {
		return Asset{}, fmt.Errorf("create generated asset directory: %w", err)
	}
	limit := s.MaxBytes
	if limit <= 0 {
		limit = defaultMaxStoreBytes
	}
	usage, err := directoryFileBytes(s.Dir)
	if err != nil {
		return Asset{}, fmt.Errorf("measure generated asset store: %w", err)
	}
	if int64(len(data)) > limit-usage {
		return Asset{}, fmt.Errorf("generated asset store quota exceeded (%d bytes)", limit)
	}
	id, err := newAssetID()
	if err != nil {
		return Asset{}, err
	}
	ext := extensionForAsset(mimeType, name, kind)
	fileName := id + "-generated" + ext
	path := filepath.Join(s.Dir, fileName)
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return Asset{}, fmt.Errorf("write generated asset: %w", err)
	}
	meta := storedAssetMeta{
		ID: id, SessionID: sessionID, Kind: kind, MIMEType: mimeType,
		Name: name, FileName: fileName,
	}
	encoded, err := json.Marshal(meta)
	if err != nil {
		_ = os.Remove(path)
		return Asset{}, fmt.Errorf("encode generated asset metadata: %w", err)
	}
	if err := os.WriteFile(filepath.Join(s.Dir, id+".json"), encoded, 0o600); err != nil {
		_ = os.Remove(path)
		return Asset{}, fmt.Errorf("write generated asset metadata: %w", err)
	}
	return Asset{
		ID: id, Kind: kind, MIMEType: mimeType, Name: name,
		URL: s.URLPrefix + "/" + id,
	}, nil
}

// Delete removes one generated asset and its metadata. It is used to roll back
// partially materialized multi-asset responses.
func (s *LocalAssetStore) Delete(id string) error {
	if s == nil {
		return errors.New("generated asset store is unavailable")
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	path, _, err := s.Resolve(id)
	if err != nil {
		return err
	}
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	if err := os.Remove(filepath.Join(s.Dir, id+".json")); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

func directoryFileBytes(dir string) (int64, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return 0, err
	}
	var total int64
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		info, err := entry.Info()
		if err != nil {
			return 0, err
		}
		total += info.Size()
	}
	return total, nil
}

// Resolve returns the durable file path and metadata for a generated asset.
func (s *LocalAssetStore) Resolve(id string) (string, storedAssetMeta, error) {
	if s == nil || !validAssetID(id) {
		return "", storedAssetMeta{}, errors.New("invalid generated asset id")
	}
	encoded, err := os.ReadFile(filepath.Join(s.Dir, id+".json"))
	if err != nil {
		return "", storedAssetMeta{}, fmt.Errorf("generated asset not found: %w", err)
	}
	var meta storedAssetMeta
	if err := json.Unmarshal(encoded, &meta); err != nil || meta.ID != id || filepath.Base(meta.FileName) != meta.FileName {
		return "", storedAssetMeta{}, errors.New("invalid generated asset metadata")
	}
	path := filepath.Join(s.Dir, meta.FileName)
	if _, err := os.Stat(path); err != nil {
		return "", storedAssetMeta{}, fmt.Errorf("generated asset file not found: %w", err)
	}
	return path, meta, nil
}

// DiskInputResolver resolves session-owned uploads and generated assets.
type DiskInputResolver struct {
	UploadDir     string
	Generated     *LocalAssetStore
	UploadOwnedBy func(sessionID, uploadID string) bool
}

// ResolveInput enforces ownership before reading any bytes from disk.
func (r *DiskInputResolver) ResolveInput(_ context.Context, sessionID, id string, expected config.MediaKind) (InputSource, error) {
	if strings.TrimSpace(sessionID) == "" || strings.TrimSpace(id) == "" {
		return InputSource{}, errors.New("session id and input id are required")
	}
	if r.Generated != nil {
		if path, meta, err := r.Generated.Resolve(id); err == nil {
			if meta.SessionID != sessionID {
				return InputSource{}, errors.New("generated input is not owned by the current session")
			}
			return readInputSource(path, meta.ID, meta.Name, meta.MIMEType, meta.Kind, expected)
		}
	}
	if r.UploadOwnedBy == nil || !r.UploadOwnedBy(sessionID, id) {
		return InputSource{}, errors.New("upload input is not owned by the current session")
	}
	entries, err := os.ReadDir(r.UploadDir)
	if err != nil {
		return InputSource{}, fmt.Errorf("read uploads: %w", err)
	}
	prefix := id + "-"
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasPrefix(entry.Name(), prefix) {
			continue
		}
		path := filepath.Join(r.UploadDir, entry.Name())
		name := strings.TrimPrefix(entry.Name(), prefix)
		mimeType := mime.TypeByExtension(strings.ToLower(filepath.Ext(name)))
		kind := mediaKindForMIME(mimeType)
		return readInputSource(path, id, name, mimeType, kind, expected)
	}
	return InputSource{}, errors.New("upload input was not found")
}

func readInputSource(path, id, name, mimeType string, kind, expected config.MediaKind) (InputSource, error) {
	info, err := os.Stat(path)
	if err != nil {
		return InputSource{}, fmt.Errorf("stat media input: %w", err)
	}
	if info.Size() > MaxGenerationInputBytes {
		return InputSource{}, fmt.Errorf("media input exceeds %d bytes", MaxGenerationInputBytes)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return InputSource{}, fmt.Errorf("read media input: %w", err)
	}
	if kind == "" {
		kind = mediaKindForExtension(filepath.Ext(name))
	}
	if expected.IsValid() && kind != expected {
		return InputSource{}, fmt.Errorf("input %s is %s, expected %s", id, kind, expected)
	}
	return InputSource{ID: id, Kind: kind, MIMEType: mimeType, Name: name, Data: data}, nil
}

// HTTPExecutor implements the common JSON create/poll/download lifecycle used
// by Volcengine Ark, MiniMax, OpenAI-compatible and custom media endpoints.
type HTTPExecutor struct {
	Resolver       InputResolver
	Store          *LocalAssetStore
	Client         *http.Client
	PollInterval   time.Duration
	MaxAssetBytes  int64
	limitOnce      sync.Once
	generationSlot chan struct{}
}

// NewHTTPExecutor constructs an executor with conservative network defaults.
func NewHTTPExecutor(resolver InputResolver, store *LocalAssetStore) *HTTPExecutor {
	return &HTTPExecutor{
		Resolver: resolver, Store: store, Client: &http.Client{Timeout: 10 * time.Minute},
		PollInterval: 2 * time.Second, MaxAssetBytes: defaultMaxAssetBytes,
	}
}

// Generate resolves input ids, dispatches the vendor request, polls async jobs,
// and materializes every returned media asset locally.
func (e *HTTPExecutor) Generate(ctx context.Context, req Request) (Result, error) {
	if !req.Operation.IsValid() || !req.Target.Valid() || !req.Dispatch.Target.Valid() {
		return Result{}, errors.New("invalid generation dispatch")
	}
	if req.Dispatch.Target != req.Target {
		return Result{}, errors.New("generation dispatch target mismatch")
	}
	e.limitOnce.Do(func() { e.generationSlot = make(chan struct{}, 1) })
	select {
	case e.generationSlot <- struct{}{}:
		defer func() { <-e.generationSlot }()
	case <-ctx.Done():
		return Result{}, ctx.Err()
	}
	timeout := time.Duration(req.Dispatch.OperationConfig.TimeoutSeconds) * time.Second
	if timeout <= 0 {
		timeout = 10 * time.Minute
	}
	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	if maximum := MaxInputRefs(req.Operation); len(req.InputRefs) > maximum {
		return Result{}, fmt.Errorf("generation operation %s accepts at most %d input references", req.Operation, maximum)
	}

	inputs, err := e.resolveInputs(ctx, req)
	if err != nil {
		return Result{}, err
	}
	normalizedOptions, err := NormalizeOptions(req.Operation, req.Options)
	if err != nil {
		return Result{}, fmt.Errorf("validate generation options: %w", err)
	}
	req.Options = normalizedOptions
	queryEndpoint := strings.TrimSpace(req.Dispatch.OperationConfig.QueryEndpoint)
	if queryEndpoint != "" && !hasTaskIDPlaceholder(queryEndpoint) {
		return Result{}, errors.New("generation query_endpoint must contain {task_id} or {id}")
	}
	payload := buildVendorPayload(req, inputs)
	createURL := endpointURL(req.Dispatch.BaseURL, req.Dispatch.OperationConfig.Endpoint, "")
	response, err := e.callJSON(ctx, http.MethodPost, createURL, req.Dispatch.APIKey, req.Dispatch.CustomHeaders, payload)
	if err != nil {
		if suggestion := suggestedAsyncCreateEndpoint(req.Dispatch.OperationConfig.Endpoint, queryEndpoint); suggestion != "" {
			return Result{}, fmt.Errorf("%w; async endpoint configuration looks inconsistent: verify whether the creation endpoint should be %s", err, suggestion)
		}
		return Result{}, err
	}
	jobID := firstStringForKeys(response, "task_id", "taskId", "id", "job_id")
	assets, err := e.materializeResponse(ctx, req.SessionID, req.Operation.OutputKind(), response, createURL)
	if err != nil {
		return Result{}, err
	}
	if len(assets) > 0 {
		return Result{JobID: jobID, Status: StatusSucceeded, Assets: assets}, nil
	}

	if jobID == "" || queryEndpoint == "" {
		status := normalizeVendorStatus(firstStringForKeys(response, "status", "state"))
		if status == StatusFailed {
			return Result{}, fmt.Errorf("generation failed: %s", responseMessage(response))
		}
		if jobID != "" {
			return Result{}, fmt.Errorf("generation endpoint returned task %s but no query_endpoint is configured", jobID)
		}
		return Result{}, fmt.Errorf("generation response contained neither an asset nor a task id: %s", responseMessage(response))
	}

	interval := e.PollInterval
	if interval <= 0 {
		interval = 2 * time.Second
	}
	for {
		if err := waitContext(ctx, interval); err != nil {
			return Result{}, fmt.Errorf("wait for generation task %s: %w", jobID, err)
		}
		queryURL := endpointURL(req.Dispatch.BaseURL, queryEndpoint, jobID)
		polled, err := e.callJSON(ctx, http.MethodGet, queryURL, req.Dispatch.APIKey, req.Dispatch.CustomHeaders, nil)
		if err != nil {
			return Result{}, fmt.Errorf("query generation task %s: %w", jobID, err)
		}
		status := normalizeVendorStatus(firstStringForKeys(polled, "status", "state", "task_status"))
		if status == StatusFailed {
			return Result{}, fmt.Errorf("generation task %s failed: %s", jobID, responseMessage(polled))
		}
		assets, err = e.materializeResponse(ctx, req.SessionID, req.Operation.OutputKind(), polled, queryURL)
		if err != nil {
			return Result{}, err
		}
		if len(assets) == 0 && status == StatusSucceeded && effectiveAdapter(req.Dispatch) == "minimax" {
			if fileID := firstStringForKeys(polled, "file_id", "fileId"); fileID != "" {
				fileURL := endpointURL(req.Dispatch.BaseURL, "/v1/files/retrieve?file_id="+url.QueryEscape(fileID), "")
				fileResponse, callErr := e.callJSON(ctx, http.MethodGet, fileURL, req.Dispatch.APIKey, req.Dispatch.CustomHeaders, nil)
				if callErr != nil {
					return Result{}, callErr
				}
				assets, err = e.materializeResponse(ctx, req.SessionID, req.Operation.OutputKind(), fileResponse, fileURL)
				if err != nil {
					return Result{}, err
				}
			}
		}
		if len(assets) > 0 {
			return Result{JobID: jobID, Status: StatusSucceeded, Assets: assets}, nil
		}
		if status == StatusSucceeded {
			return Result{}, fmt.Errorf("generation task %s succeeded without a media asset", jobID)
		}
	}
}

func (e *HTTPExecutor) resolveInputs(ctx context.Context, req Request) ([]InputSource, error) {
	if len(req.InputRefs) == 0 {
		return nil, nil
	}
	if e.Resolver == nil {
		return nil, errors.New("generation input resolver is unavailable")
	}
	expected := req.Operation.RequiredInputKind()
	inputs := make([]InputSource, 0, len(req.InputRefs))
	var totalBytes int64
	for _, ref := range req.InputRefs {
		source, err := e.Resolver.ResolveInput(ctx, req.SessionID, ref, expected)
		if err != nil {
			return nil, fmt.Errorf("resolve input %s: %w", ref, err)
		}
		totalBytes += int64(len(source.Data))
		if totalBytes > MaxGenerationInputBytes {
			return nil, fmt.Errorf("generation inputs exceed %d bytes", MaxGenerationInputBytes)
		}
		inputs = append(inputs, source)
	}
	return inputs, nil
}

func buildVendorPayload(req Request, inputs []InputSource) map[string]any {
	dataURLs := make([]string, 0, len(inputs))
	for _, input := range inputs {
		mimeType := input.MIMEType
		if mimeType == "" {
			mimeType = defaultMIME(input.Kind)
		}
		dataURLs = append(dataURLs, "data:"+mimeType+";base64,"+base64.StdEncoding.EncodeToString(input.Data))
	}
	return providerstrategy.BuildGenerationPayload(providerstrategy.GenerationPayloadRequest{
		Adapter:       effectiveAdapter(req.Dispatch),
		Operation:     req.Operation,
		Model:         req.Target.Model,
		Prompt:        req.Prompt,
		Endpoint:      req.Dispatch.OperationConfig.Endpoint,
		DefaultParams: req.Dispatch.OperationConfig.DefaultParams,
		Options:       req.Options,
		InputDataURLs: dataURLs,
	})
}

func (e *HTTPExecutor) callJSON(ctx context.Context, method, endpoint, apiKey string, customHeaders map[string]string, payload map[string]any) (map[string]any, error) {
	if strings.TrimSpace(endpoint) == "" {
		return nil, errors.New("generation endpoint is empty")
	}
	var body io.Reader
	if payload != nil {
		encoded, err := json.Marshal(payload)
		if err != nil {
			return nil, fmt.Errorf("encode generation request: %w", err)
		}
		body = bytes.NewReader(encoded)
	}
	request, err := http.NewRequestWithContext(ctx, method, endpoint, body)
	if err != nil {
		return nil, fmt.Errorf("build generation request: %w", err)
	}
	request.Header.Set("Accept", "application/json")
	if payload != nil {
		request.Header.Set("Content-Type", "application/json")
	}
	if apiKey != "" {
		request.Header.Set("Authorization", "Bearer "+apiKey)
		request.Header.Set("x-api-key", apiKey)
	}
	if err := requestheader.Apply(ctx, request.Header, customHeaders); err != nil {
		return nil, fmt.Errorf("apply generation custom headers: %w", err)
	}
	client := e.Client
	if client == nil {
		client = http.DefaultClient
	}
	response, err := client.Do(request)
	if err != nil {
		return nil, fmt.Errorf("generation request: %w", err)
	}
	defer response.Body.Close()
	encoded, err := io.ReadAll(io.LimitReader(response.Body, 8<<20))
	if err != nil {
		return nil, fmt.Errorf("read generation response: %w", err)
	}
	if response.StatusCode < 200 || response.StatusCode >= 300 {
		return nil, fmt.Errorf("generation endpoint returned %s: %s", response.Status, strings.TrimSpace(string(encoded)))
	}
	var parsed map[string]any
	if err := json.Unmarshal(encoded, &parsed); err != nil {
		return nil, fmt.Errorf("decode generation response: %w", err)
	}
	return parsed, nil
}

type assetCandidate struct {
	URL      string
	Data     []byte
	MIMEType string
	Name     string
}

func (e *HTTPExecutor) materializeResponse(ctx context.Context, sessionID string, kind config.MediaKind, response map[string]any, trustedEndpoint string) ([]Asset, error) {
	if e.Store == nil {
		return nil, errors.New("generated asset store is unavailable")
	}
	candidates := collectAssetCandidates(response, kind)
	if len(candidates) > maxAssetsPerResponse {
		return nil, fmt.Errorf("generation response contains %d assets; maximum is %d", len(candidates), maxAssetsPerResponse)
	}
	assets := make([]Asset, 0, len(candidates))
	committed := false
	defer func() {
		if committed {
			return
		}
		for _, asset := range assets {
			_ = e.Store.Delete(asset.ID)
		}
	}()
	seen := make(map[string]struct{}, len(candidates))
	var totalBytes int64
	for _, candidate := range candidates {
		key := candidate.URL
		if key == "" {
			digest := sha256.Sum256(candidate.Data)
			key = fmt.Sprintf("inline:%x", digest)
		}
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		data := candidate.Data
		mimeType := candidate.MIMEType
		name := candidate.Name
		if candidate.URL != "" {
			var err error
			data, mimeType, name, err = e.downloadAsset(ctx, candidate.URL, trustedEndpoint, kind, maxAssetResponseBytes-totalBytes)
			if err != nil {
				return nil, err
			}
		}
		totalBytes += int64(len(data))
		if totalBytes > maxAssetResponseBytes {
			return nil, fmt.Errorf("generated assets exceed %d bytes in one response", maxAssetResponseBytes)
		}
		mimeType, err := normalizeAssetMIME(kind, mimeType)
		if err != nil {
			return nil, err
		}
		asset, err := e.Store.Save(sessionID, kind, mimeType, name, data)
		if err != nil {
			return nil, err
		}
		assets = append(assets, asset)
	}
	committed = true
	return assets, nil
}

func (e *HTTPExecutor) downloadAsset(ctx context.Context, rawURL, trustedEndpoint string, kind config.MediaKind, remainingBytes int64) ([]byte, string, string, error) {
	client, parsedURL, err := newPinnedAssetClient(ctx, e.Client, rawURL, trustedEndpoint)
	if err != nil {
		return nil, "", "", err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, rawURL, nil)
	if err != nil {
		return nil, "", "", fmt.Errorf("build generated asset download: %w", err)
	}
	response, err := client.Do(request)
	if err != nil {
		return nil, "", "", fmt.Errorf("download generated asset: %w", err)
	}
	defer response.Body.Close()
	if response.StatusCode < 200 || response.StatusCode >= 300 {
		return nil, "", "", fmt.Errorf("generated asset download returned %s", response.Status)
	}
	limit := e.MaxAssetBytes
	if limit <= 0 {
		limit = defaultMaxAssetBytes
	}
	if remainingBytes <= 0 {
		return nil, "", "", fmt.Errorf("generated assets exceed %d bytes in one response", maxAssetResponseBytes)
	}
	if remainingBytes < limit {
		limit = remainingBytes
	}
	if response.ContentLength > limit {
		return nil, "", "", fmt.Errorf("generated asset exceeds %d bytes", limit)
	}
	data, err := io.ReadAll(io.LimitReader(response.Body, limit+1))
	if err != nil {
		return nil, "", "", fmt.Errorf("read generated asset: %w", err)
	}
	if int64(len(data)) > limit {
		return nil, "", "", fmt.Errorf("generated asset exceeds %d bytes", limit)
	}
	name := filepath.Base(parsedURL.Path)
	mimeType := strings.TrimSpace(strings.Split(response.Header.Get("Content-Type"), ";")[0])
	if mimeType == "" {
		mimeType = defaultMIME(kind)
	}
	return data, mimeType, name, nil
}

func effectiveAdapter(dispatch Dispatch) string {
	adapter := config.NormalizeGenerationVendor(dispatch.Adapter)
	if strategyAdapter := providerstrategy.GenerationAdapter(providerstrategy.GenerationAdapterRequest{
		ProviderID:        dispatch.ProviderID,
		Protocol:          dispatch.Protocol,
		ConfiguredAdapter: adapter,
	}); strategyAdapter != "" {
		adapter = strategyAdapter
	}
	if dispatch.ProviderID == "" || dispatch.ProviderID == config.ProviderIDCustom {
		// Legacy/custom providers can still route old media endpoints without
		// requiring the user to re-enter a model-level adapter.
		if inferred := inferAdapterFromEndpoint(dispatch.OperationConfig.Endpoint); inferred != "" && (adapter == "" || adapter == "openai" || adapter == "anthropic") {
			return inferred
		}
	}
	if adapter != "" {
		return adapter
	}
	return config.NormalizeGenerationVendor(dispatch.Vendor)
}

func inferAdapterFromEndpoint(endpoint string) string {
	path := strings.ToLower(strings.TrimSpace(endpoint))
	if parsed, err := url.Parse(path); err == nil && parsed.Path != "" {
		path = strings.TrimRight(parsed.Path, "/")
	}
	switch {
	case strings.HasSuffix(path, "/contents/generations/tasks"):
		return "volcengine"
	case strings.HasSuffix(path, "/video_generation"),
		strings.HasSuffix(path, "/image_generation"),
		strings.HasSuffix(path, "/t2a_v2"),
		strings.HasSuffix(path, "/music_generation"):
		return "minimax"
	case strings.HasSuffix(path, "/images/generations"):
		return "openai"
	default:
		return ""
	}
}

func validateRemoteAssetURL(ctx context.Context, rawURL, trustedEndpoint string) error {
	_, _, err := resolveAssetTarget(ctx, rawURL, trustedEndpoint)
	return err
}

// newPinnedAssetClient validates every asset host, disables proxies, and
// ensures the transport connects only to the IP addresses resolved during
// validation. Redirect targets are validated and pinned before they are used.
func newPinnedAssetClient(ctx context.Context, base *http.Client, rawURL, trustedEndpoint string) (*http.Client, *url.URL, error) {
	if base == nil {
		base = http.DefaultClient
	}
	transport, err := cloneAssetTransport(base.Transport)
	if err != nil {
		return nil, nil, err
	}
	parsed, addresses, err := resolveAssetTarget(ctx, rawURL, trustedEndpoint)
	if err != nil {
		return nil, nil, err
	}

	pins := map[string][]net.IP{assetDialKey(parsed): cloneIPs(addresses)}
	var pinsMu sync.RWMutex
	transport.Proxy = nil
	transport.DialContext = func(dialCtx context.Context, network, address string) (net.Conn, error) {
		key, port, err := normalizeDialAddress(address)
		if err != nil {
			return nil, err
		}
		pinsMu.RLock()
		allowed := cloneIPs(pins[key])
		pinsMu.RUnlock()
		if len(allowed) == 0 {
			return nil, fmt.Errorf("generated asset transport refused unvalidated host %s", address)
		}
		dialer := net.Dialer{Timeout: 30 * time.Second, KeepAlive: 30 * time.Second}
		var failures []error
		for _, addressIP := range allowed {
			connection, dialErr := dialer.DialContext(dialCtx, network, net.JoinHostPort(addressIP.String(), port))
			if dialErr == nil {
				return connection, nil
			}
			failures = append(failures, dialErr)
		}
		return nil, fmt.Errorf("connect to validated generated asset host %s: %w", address, errors.Join(failures...))
	}

	clientCopy := *base
	clientCopy.Transport = transport
	previousRedirectCheck := base.CheckRedirect
	clientCopy.CheckRedirect = func(redirect *http.Request, via []*http.Request) error {
		redirectURL, redirectAddresses, resolveErr := resolveAssetTarget(redirect.Context(), redirect.URL.String(), trustedEndpoint)
		if resolveErr != nil {
			return resolveErr
		}
		pinsMu.Lock()
		pins[assetDialKey(redirectURL)] = cloneIPs(redirectAddresses)
		pinsMu.Unlock()
		if previousRedirectCheck != nil {
			return previousRedirectCheck(redirect, via)
		}
		if len(via) >= 10 {
			return errors.New("stopped after 10 redirects")
		}
		return nil
	}
	return &clientCopy, parsed, nil
}

func cloneAssetTransport(roundTripper http.RoundTripper) (*http.Transport, error) {
	if roundTripper == nil {
		roundTripper = http.DefaultTransport
	}
	transport, ok := roundTripper.(*http.Transport)
	if !ok {
		return nil, fmt.Errorf("generated asset download requires *http.Transport, got %T", roundTripper)
	}
	return transport.Clone(), nil
}

func resolveAssetTarget(ctx context.Context, rawURL, trustedEndpoint string) (*url.URL, []net.IP, error) {
	parsed, err := url.Parse(strings.TrimSpace(rawURL))
	if err != nil || parsed.Hostname() == "" || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.User != nil {
		return nil, nil, errors.New("generated asset URL must be an http(s) URL without embedded credentials")
	}
	hostname := strings.TrimSuffix(strings.ToLower(parsed.Hostname()), ".")
	allowPrivate := sameOrigin(parsed, trustedEndpoint)
	if !allowPrivate && (hostname == "localhost" || strings.HasSuffix(hostname, ".localhost")) {
		return nil, nil, fmt.Errorf("generated asset URL targets a local host: %s", hostname)
	}
	addresses := []net.IP{}
	if literal := net.ParseIP(hostname); literal != nil {
		addresses = append(addresses, literal)
	} else {
		resolved, lookupErr := net.DefaultResolver.LookupIPAddr(ctx, hostname)
		if lookupErr != nil {
			return nil, nil, fmt.Errorf("resolve generated asset host %s: %w", hostname, lookupErr)
		}
		for _, address := range resolved {
			addresses = append(addresses, address.IP)
		}
	}
	if len(addresses) == 0 {
		return nil, nil, fmt.Errorf("generated asset host %s resolved to no addresses", hostname)
	}
	if !allowPrivate {
		for _, address := range addresses {
			if !address.IsGlobalUnicast() || address.IsPrivate() || address.IsLoopback() || address.IsLinkLocalUnicast() || address.IsLinkLocalMulticast() || address.IsUnspecified() {
				return nil, nil, fmt.Errorf("generated asset URL targets a non-public address: %s", address)
			}
		}
	}
	return parsed, addresses, nil
}

func assetDialKey(parsed *url.URL) string {
	port := parsed.Port()
	if port == "" {
		if parsed.Scheme == "https" {
			port = "443"
		} else {
			port = "80"
		}
	}
	return net.JoinHostPort(strings.TrimSuffix(strings.ToLower(parsed.Hostname()), "."), port)
}

func normalizeDialAddress(address string) (string, string, error) {
	host, port, err := net.SplitHostPort(address)
	if err != nil {
		return "", "", fmt.Errorf("parse generated asset dial address %q: %w", address, err)
	}
	host = strings.TrimSuffix(strings.ToLower(host), ".")
	return net.JoinHostPort(host, port), port, nil
}

func cloneIPs(source []net.IP) []net.IP {
	cloned := make([]net.IP, len(source))
	for index, address := range source {
		cloned[index] = append(net.IP(nil), address...)
	}
	return cloned
}

func sameOrigin(candidate *url.URL, trustedEndpoint string) bool {
	trusted, err := url.Parse(strings.TrimSpace(trustedEndpoint))
	return err == nil && strings.EqualFold(candidate.Scheme, trusted.Scheme) && strings.EqualFold(candidate.Host, trusted.Host)
}

func normalizeAssetMIME(kind config.MediaKind, value string) (string, error) {
	value = strings.ToLower(strings.TrimSpace(strings.Split(value, ";")[0]))
	if value == "" || value == "application/octet-stream" {
		return defaultMIME(kind), nil
	}
	wantedPrefix := string(kind) + "/"
	if !strings.HasPrefix(value, wantedPrefix) || value == "image/svg+xml" {
		return "", fmt.Errorf("generated %s asset returned unsafe MIME type %q", kind, value)
	}
	return value, nil
}

func collectAssetCandidates(value any, kind config.MediaKind) []assetCandidate {
	var out []assetCandidate
	var walk func(any, string)
	walk = func(current any, key string) {
		switch typed := current.(type) {
		case map[string]any:
			for childKey, child := range typed {
				walk(child, strings.ToLower(childKey))
			}
		case []any:
			for _, child := range typed {
				walk(child, key)
			}
		case string:
			trimmed := strings.TrimSpace(typed)
			if trimmed == "" {
				return
			}
			switch key {
			case "url", "urls", "download_url", "file_url", "image_url", "image_urls", "video_url", "video_urls", "audio_url", "audio_urls":
				if strings.HasPrefix(trimmed, "http://") || strings.HasPrefix(trimmed, "https://") {
					out = append(out, assetCandidate{URL: trimmed})
				} else if strings.HasPrefix(trimmed, "data:") {
					if candidate, ok := decodeDataURI(trimmed); ok {
						out = append(out, candidate)
					}
				}
			case "b64_json", "base64", "image_base64", "audio", "audio_file":
				// MiniMax may return audio_file as a hexadecimal string. Hex text
				// is also accepted by many base64 decoders, so try hex first for
				// audio-specific fields to avoid silently corrupting the asset.
				if (key == "audio" || key == "audio_file") && kind == config.MediaAudio {
					if data, err := hex.DecodeString(trimmed); err == nil && len(data) > 0 {
						out = append(out, assetCandidate{Data: data, MIMEType: defaultMIME(kind)})
						return
					}
				}
				if data, err := base64.StdEncoding.DecodeString(trimmed); err == nil && len(data) > 0 {
					out = append(out, assetCandidate{Data: data, MIMEType: defaultMIME(kind)})
				}
			}
		}
	}
	walk(value, "")
	return out
}

func decodeDataURI(value string) (assetCandidate, bool) {
	header, encoded, ok := strings.Cut(value, ",")
	if !ok || !strings.Contains(header, ";base64") {
		return assetCandidate{}, false
	}
	data, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil || len(data) == 0 {
		return assetCandidate{}, false
	}
	mimeType := strings.TrimPrefix(strings.Split(header, ";")[0], "data:")
	return assetCandidate{Data: data, MIMEType: mimeType}, true
}

func endpointURL(baseURL, endpoint, taskID string) string {
	escapedTaskID := url.PathEscape(taskID)
	endpoint = strings.NewReplacer(
		"{task_id}", escapedTaskID,
		"{id}", escapedTaskID,
	).Replace(strings.TrimSpace(endpoint))
	return config.JoinAPIURL(baseURL, endpoint)
}

func hasTaskIDPlaceholder(endpoint string) bool {
	return strings.Contains(endpoint, "{task_id}") || strings.Contains(endpoint, "{id}")
}

func suggestedAsyncCreateEndpoint(createEndpoint, queryEndpoint string) string {
	createEndpoint = strings.TrimRight(strings.TrimSpace(createEndpoint), "/")
	queryEndpoint = strings.TrimSpace(queryEndpoint)
	if createEndpoint == "" || queryEndpoint == "" {
		return ""
	}
	placeholderIndex := -1
	for _, placeholder := range []string{"{task_id}", "{id}"} {
		if index := strings.Index(queryEndpoint, placeholder); index >= 0 && (placeholderIndex < 0 || index < placeholderIndex) {
			placeholderIndex = index
		}
	}
	if placeholderIndex < 0 {
		return ""
	}
	taskCollection := strings.TrimRight(queryEndpoint[:placeholderIndex], "/")
	if taskCollection != createEndpoint && strings.HasPrefix(taskCollection, createEndpoint+"/") {
		return taskCollection
	}
	return ""
}

func firstStringForKeys(value any, keys ...string) string {
	// Search one requested key at a time so caller priority is deterministic;
	// ranging over a Go map would otherwise make e.g. task_id vs id random.
	for _, key := range keys {
		if found := firstStringForKey(value, strings.ToLower(key)); found != "" {
			return found
		}
	}
	return ""
}

func firstStringForKey(value any, wanted string) string {
	switch typed := value.(type) {
	case map[string]any:
		for key, child := range typed {
			if strings.ToLower(key) != wanted {
				continue
			}
			if text, ok := child.(string); ok && strings.TrimSpace(text) != "" {
				return strings.TrimSpace(text)
			}
		}
		for _, child := range typed {
			if found := firstStringForKey(child, wanted); found != "" {
				return found
			}
		}
	case []any:
		for _, child := range typed {
			if found := firstStringForKey(child, wanted); found != "" {
				return found
			}
		}
	}
	return ""
}

func normalizeVendorStatus(value string) Status {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "success", "succeeded", "completed", "done", "finish", "finished":
		return StatusSucceeded
	case "fail", "failed", "failure", "error", "cancelled", "canceled":
		return StatusFailed
	case "queued", "pending", "submitted", "created":
		return StatusQueued
	default:
		return StatusRunning
	}
}

func responseMessage(response map[string]any) string {
	if message := firstStringForKeys(response, "message", "error", "reason", "fail_reason"); message != "" {
		return message
	}
	encoded, _ := json.Marshal(response)
	if len(encoded) > 1000 {
		encoded = encoded[:1000]
	}
	return string(encoded)
}

func waitContext(ctx context.Context, duration time.Duration) error {
	timer := time.NewTimer(duration)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}

func newAssetID() (string, error) {
	var value [8]byte
	if _, err := rand.Read(value[:]); err != nil {
		return "", fmt.Errorf("create generated asset id: %w", err)
	}
	return hex.EncodeToString(value[:]), nil
}

func validAssetID(value string) bool {
	if len(value) != 16 {
		return false
	}
	_, err := hex.DecodeString(value)
	return err == nil
}

func extensionForAsset(mimeType, name string, kind config.MediaKind) string {
	if ext := strings.ToLower(filepath.Ext(name)); ext != "" && len(ext) <= 8 {
		return ext
	}
	if extensions, _ := mime.ExtensionsByType(mimeType); len(extensions) > 0 {
		return extensions[0]
	}
	switch kind {
	case config.MediaImage:
		return ".png"
	case config.MediaVideo:
		return ".mp4"
	case config.MediaAudio:
		return ".mp3"
	default:
		return ".bin"
	}
}

func defaultMIME(kind config.MediaKind) string {
	switch kind {
	case config.MediaImage:
		return "image/png"
	case config.MediaVideo:
		return "video/mp4"
	case config.MediaAudio:
		return "audio/mpeg"
	default:
		return "application/octet-stream"
	}
}

func mediaKindForMIME(value string) config.MediaKind {
	switch {
	case strings.HasPrefix(value, "image/"):
		return config.MediaImage
	case strings.HasPrefix(value, "video/"):
		return config.MediaVideo
	case strings.HasPrefix(value, "audio/"):
		return config.MediaAudio
	default:
		return ""
	}
}

func mediaKindForExtension(value string) config.MediaKind {
	switch strings.ToLower(value) {
	case ".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp":
		return config.MediaImage
	case ".mp4", ".webm", ".mov", ".mkv", ".m4v":
		return config.MediaVideo
	case ".mp3", ".wav", ".m4a", ".ogg", ".flac", ".opus", ".aac":
		return config.MediaAudio
	default:
		return ""
	}
}
