// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';

export function ServeHTTP(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;
