// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream(arg1) {
  return window['go']['main']['App']['CancelStream'](arg1);
}

export function CancelWindowClose() {
  return window['go']['main']['App']['CancelWindowClose']();
}

export function ConfirmWindowClose(arg1) {
  return window['go']['main']['App']['ConfirmWindowClose'](arg1);
}

export function GetApplicationTitle() {
  return window['go']['main']['App']['GetApplicationTitle']();
}

export function GetBackendURL() {
  return window['go']['main']['App']['GetBackendURL']();
}

export function InstallUpdate(arg1, arg2) {
  return window['go']['main']['App']['InstallUpdate'](arg1, arg2);
}

export function OpenExplorer(arg1) {
  return window['go']['main']['App']['OpenExplorer'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RequestWindowClose() {
  return window['go']['main']['App']['RequestWindowClose']();
}

export function SaveDownloadFile(arg1, arg2) {
  return window['go']['main']['App']['SaveDownloadFile'](arg1, arg2);
}

export function SaveExportFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveExportFile'](arg1, arg2, arg3);
}

export function ServeHTTP(arg1, arg2) {
  return window['go']['main']['App']['ServeHTTP'](arg1, arg2);
}

export function SetNoMoreConfirm() {
  return window['go']['main']['App']['SetNoMoreConfirm']();
}

export function StreamMessages(arg1, arg2) {
  return window['go']['main']['App']['StreamMessages'](arg1, arg2);
}
