// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream(arg1) {
  return window['go']['main']['App']['CancelStream'](arg1);
}

export function GetBackendURL() {
  return window['go']['main']['App']['GetBackendURL']();
}

export function OpenExplorer(arg1) {
  return window['go']['main']['App']['OpenExplorer'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function ServeHTTP(arg1, arg2) {
  return window['go']['main']['App']['ServeHTTP'](arg1, arg2);
}

export function StreamMessages(arg1, arg2) {
  return window['go']['main']['App']['StreamMessages'](arg1, arg2);
}
