// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';

export function CancelStream(arg1:string):Promise<void>;

export function CancelWindowClose():Promise<void>;

export function ConfirmWindowClose(arg1:string):Promise<void>;

export function GetBackendURL():Promise<string>;

export function OpenExplorer(arg1:string):Promise<void>;

export function OpenTerminal(arg1:string):Promise<void>;

export function ServeHTTP(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function StreamMessages(arg1:string,arg2:string):Promise<number>;
